import Foundation
import AppKit
import UniformTypeIdentifiers
import OSLog

/// Reads and normalizes diverse pasteboard representations (Images, Finder File URLs, Web URLs, RTF, HTML, Plain Text).
public final class ClipboardReader: Sendable {
    private let logger = Logger(subsystem: "com.clipbo.app", category: "ClipboardReader")

    public init() {}

    /// Reads the current contents of the given pasteboard and parses it into a normalized `PasteboardPayload`.
    public func read(
        from pasteboard: NSPasteboard = .general,
        frontmostApp: (bundleId: String?, name: String?)? = nil
    ) -> PasteboardPayload? {
        let types = pasteboard.types ?? []
        guard !types.isEmpty else { return nil }

        // Respect concealed/password manager pasteboard flags
        let concealedTypes: [NSPasteboard.PasteboardType] = [
            NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
            NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
            NSPasteboard.PasteboardType("com.agilebits.onepassword")
        ]
        for concealed in concealedTypes {
            if types.contains(concealed) {
                logger.debug("Ignoring concealed/transient pasteboard data")
                return nil
            }
        }

        // Get frontmost application context if available
        let bundleId = frontmostApp?.bundleId ?? NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        let appName = frontmostApp?.name ?? NSWorkspace.shared.frontmostApplication?.localizedName

        // 1. Check for Image content first (PNG, TIFF, NSImage)
        if let imageData = readImageData(from: pasteboard) {
            var width: Double? = nil
            var height: Double? = nil
            if let image = NSImage(data: imageData) {
                width = Double(image.size.width)
                height = Double(image.size.height)
            }
            logger.info("Captured image payload (\(imageData.count) bytes)")
            return PasteboardPayload.image(
                data: imageData,
                width: width,
                height: height,
                sourceAppBundleId: bundleId,
                sourceAppName: appName
            )
        }

        // 2. Check for Finder File URLs (public.file-url) - Extract metadata without reading file contents
        if let filePayload = readFileReference(from: pasteboard, bundleId: bundleId, appName: appName) {
            logger.info("Captured Finder file reference payload: \(filePayload.fileName ?? "unknown")")
            return filePayload
        }

        // 3. Check for Web URL content (public.url or isolated http/https)
        if let webURLString = readWebURLString(from: pasteboard) {
            logger.info("Captured Web URL payload")
            return PasteboardPayload.url(
                webURLString,
                sourceAppBundleId: bundleId,
                sourceAppName: appName
            )
        }

        // 4. Check for RTF (public.rtf) representation
        if types.contains(.rtf), let rtfPayload = readRTF(from: pasteboard, bundleId: bundleId, appName: appName) {
            logger.info("Captured normalized RTF text payload (\(rtfPayload.textContent?.count ?? 0) chars)")
            return rtfPayload
        }

        // 5. Check for HTML (public.html) representation
        if types.contains(.html), let htmlPayload = readHTML(from: pasteboard, bundleId: bundleId, appName: appName) {
            logger.info("Captured normalized HTML text payload (\(htmlPayload.textContent?.count ?? 0) chars)")
            return htmlPayload
        }

        // 6. Check for Plain Text (.string / public.utf8-plain-text)
        if let stringContent = pasteboard.string(forType: .string) {
            let trimmed = stringContent.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return nil }

            if isValidWebURL(trimmed) {
                return PasteboardPayload.url(
                    trimmed,
                    sourceAppBundleId: bundleId,
                    sourceAppName: appName
                )
            }

            logger.info("Captured plain text payload (\(stringContent.count) chars)")
            return PasteboardPayload.text(
                stringContent,
                sourceAppBundleId: bundleId,
                sourceAppName: appName
            )
        }

        return nil
    }

    // MARK: - Finder File Reference Reading
    private func readFileReference(
        from pasteboard: NSPasteboard,
        bundleId: String?,
        appName: String?
    ) -> PasteboardPayload? {
        // Read file URLs from pasteboard objects
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [NSPasteboard.ReadingOptionKey.urlReadingFileURLsOnly: true]) as? [URL],
           let firstURL = urls.first, firstURL.isFileURL {
            return makeFilePayload(url: firstURL, bundleId: bundleId, appName: appName)
        }

        // Check for .fileURL pasteboard type string
        if let fileURLString = pasteboard.string(forType: .fileURL),
           let url = URL(string: fileURLString), url.isFileURL {
            return makeFilePayload(url: url, bundleId: bundleId, appName: appName)
        }

        // Check legacy NSFilenamesPboardType
        let filenamesType = NSPasteboard.PasteboardType("NSFilenamesPboardType")
        if let paths = pasteboard.propertyList(forType: filenamesType) as? [String],
           let firstPath = paths.first {
            let url = URL(fileURLWithPath: firstPath)
            return makeFilePayload(url: url, bundleId: bundleId, appName: appName)
        }

        return nil
    }

    private func makeFilePayload(url: URL, bundleId: String?, appName: String?) -> PasteboardPayload {
        let filename = url.lastPathComponent
        var utiString: String? = nil

        if let contentType = try? url.resourceValues(forKeys: [.contentTypeKey]).contentType {
            utiString = contentType.identifier
        } else {
            let ext = url.pathExtension
            if !ext.isEmpty, let utType = UTType(filenameExtension: ext) {
                utiString = utType.identifier
            }
        }

        return PasteboardPayload.file(
            url: url,
            fileName: filename,
            fileUTI: utiString,
            sourceAppBundleId: bundleId,
            sourceAppName: appName
        )
    }

    // MARK: - RTF Reading & Normalization
    public func readRTF(
        from pasteboard: NSPasteboard,
        bundleId: String? = nil,
        appName: String? = nil
    ) -> PasteboardPayload? {
        guard let rtfData = pasteboard.data(forType: .rtf), !rtfData.isEmpty else {
            return nil
        }

        guard let attributed = try? NSAttributedString(
            data: rtfData,
            options: [.documentType: NSAttributedString.DocumentType.rtf],
            documentAttributes: nil
        ) else {
            logger.debug("Failed to decode RTF data, falling back")
            return nil
        }

        let rawString = attributed.string
        let trimmed = rawString.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        return PasteboardPayload.rtf(
            text: rawString,
            sourceAppBundleId: bundleId,
            sourceAppName: appName
        )
    }

    // MARK: - HTML Reading & Normalization
    public func readHTML(
        from pasteboard: NSPasteboard,
        bundleId: String? = nil,
        appName: String? = nil
    ) -> PasteboardPayload? {
        guard let htmlData = pasteboard.data(forType: .html), !htmlData.isEmpty else {
            return nil
        }

        // Safe conversion of HTML data to clean plain text
        if let attributed = try? NSAttributedString(
            data: htmlData,
            options: [
                .documentType: NSAttributedString.DocumentType.html,
                .characterEncoding: String.Encoding.utf8.rawValue
            ],
            documentAttributes: nil
        ) {
            let rawString = attributed.string
            let trimmed = rawString.trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmed.isEmpty {
                return PasteboardPayload.html(
                    text: rawString,
                    sourceAppBundleId: bundleId,
                    sourceAppName: appName
                )
            }
        }

        // Fallback: strip basic tags if NSAttributedString html parsing yields empty
        if let htmlString = String(data: htmlData, encoding: .utf8) {
            let stripped = stripHTMLTags(htmlString).trimmingCharacters(in: .whitespacesAndNewlines)
            if !stripped.isEmpty {
                return PasteboardPayload.html(
                    text: stripped,
                    sourceAppBundleId: bundleId,
                    sourceAppName: appName
                )
            }
        }

        return nil
    }

    private func stripHTMLTags(_ str: String) -> String {
        str.replacingOccurrences(of: "<[^>]+>", with: "", options: .regularExpression, range: nil)
    }

    // MARK: - Web URL Reading
    private func readWebURLString(from pasteboard: NSPasteboard) -> String? {
        // Direct .URL pasteboard type
        if let url = pasteboard.string(forType: .URL), !url.isEmpty, isValidWebURL(url) {
            return url
        }

        // Web URL objects
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           let first = urls.first, !first.isFileURL, isValidWebURL(first.absoluteString) {
            return first.absoluteString
        }

        return nil
    }

    // MARK: - Image Reading
    private func readImageData(from pasteboard: NSPasteboard) -> Data? {
        // Direct PNG data
        if let pngData = pasteboard.data(forType: .png), !pngData.isEmpty {
            return pngData
        }
        // TIFF representation converted to PNG
        if let tiffData = pasteboard.data(forType: .tiff), !tiffData.isEmpty {
            if let bitmap = NSBitmapImageRep(data: tiffData),
               let pngData = bitmap.representation(using: .png, properties: [:]) {
                return pngData
            }
            return tiffData
        }
        // Reading NSImage objects from pasteboard
        if let images = pasteboard.readObjects(forClasses: [NSImage.self], options: nil) as? [NSImage],
           let firstImage = images.first,
           let tiffData = firstImage.tiffRepresentation {
            if let bitmap = NSBitmapImageRep(data: tiffData),
               let pngData = bitmap.representation(using: .png, properties: [:]) {
                return pngData
            }
            return tiffData
        }
        return nil
    }

    private func isValidWebURL(_ string: String) -> Bool {
        guard let url = URL(string: string), let scheme = url.scheme?.lowercased() else {
            return false
        }
        return (scheme == "http" || scheme == "https" || scheme == "ftp") && url.host != nil
    }
}
