import Foundation
import AppKit
import OSLog

public enum ClipboardWriterError: LocalizedError, Sendable {
    case emptyContent
    case imageLoadFailed
    case writeFailed

    public var errorDescription: String? {
        switch self {
        case .emptyContent:
            return "Cannot write empty content to pasteboard"
        case .imageLoadFailed:
            return "Could not load image data for pasteboard restoration"
        case .writeFailed:
            return "Failed to write data to pasteboard"
        }
    }
}

/// Restores stored clips back to the macOS pasteboard.
public final class ClipboardWriter: @unchecked Sendable {
    private let logger = Logger(subsystem: "com.clipbo.app", category: "ClipboardWriter")
    private let imageStorage: ImageStorage
    
    /// Thread-safe tracker of pasteboard change counts produced by ClipBo's own write operations.
    private let lock = NSLock()
    private var _lastWrittenChangeCounts: Set<Int> = []

    public init(imageStorage: ImageStorage = ImageStorage()) {
        self.imageStorage = imageStorage
    }

    /// Checks whether a given change count was generated by this writer.
    public func isSelfWrite(changeCount: Int) -> Bool {
        lock.lock()
        defer { lock.unlock() }
        return _lastWrittenChangeCounts.contains(changeCount)
    }

    /// Records a change count as originating from ClipBo.
    private func recordWrittenChangeCount(_ count: Int) {
        lock.lock()
        defer { lock.unlock() }
        _lastWrittenChangeCounts.insert(count)
        // Keep the set bounded to avoid memory growth
        if _lastWrittenChangeCounts.count > 50 {
            let sorted = _lastWrittenChangeCounts.sorted()
            _lastWrittenChangeCounts = Set(sorted.suffix(25))
        }
    }

    /// Writes a text string to the pasteboard.
    public func writeText(_ text: String, to pasteboard: NSPasteboard = .general) throws {
        guard !text.isEmpty else {
            throw ClipboardWriterError.emptyContent
        }

        pasteboard.clearContents()
        guard pasteboard.setString(text, forType: .string) else {
            throw ClipboardWriterError.writeFailed
        }

        recordWrittenChangeCount(pasteboard.changeCount)
        logger.debug("Successfully wrote text clip to pasteboard (changeCount: \(pasteboard.changeCount))")
    }

    /// Writes a URL to the pasteboard with URL and string types.
    public func writeURL(_ urlString: String, to pasteboard: NSPasteboard = .general) throws {
        guard !urlString.isEmpty else {
            throw ClipboardWriterError.emptyContent
        }

        pasteboard.clearContents()
        pasteboard.declareTypes([.string, .URL], owner: nil)
        pasteboard.setString(urlString, forType: .string)
        if let url = URL(string: urlString) {
            pasteboard.setString(url.absoluteString, forType: .URL)
        }

        recordWrittenChangeCount(pasteboard.changeCount)
        logger.debug("Successfully wrote URL clip to pasteboard (changeCount: \(pasteboard.changeCount))")
    }

    /// Writes image data to the pasteboard.
    public func writeImageData(_ imageData: Data, to pasteboard: NSPasteboard = .general) throws {
        guard !imageData.isEmpty else {
            throw ClipboardWriterError.emptyContent
        }

        guard let image = NSImage(data: imageData) else {
            throw ClipboardWriterError.imageLoadFailed
        }

        pasteboard.clearContents()
        guard pasteboard.writeObjects([image]) else {
            throw ClipboardWriterError.writeFailed
        }

        recordWrittenChangeCount(pasteboard.changeCount)
        logger.debug("Successfully wrote image clip to pasteboard (changeCount: \(pasteboard.changeCount))")
    }

    /// Writes an image referenced by filename in `ImageStorage` to the pasteboard.
    public func writeImage(filenameOrPath: String, to pasteboard: NSPasteboard = .general) throws {
        guard let data = imageStorage.loadImage(filenameOrPath: filenameOrPath) else {
            throw ClipboardWriterError.imageLoadFailed
        }
        try writeImageData(data, to: pasteboard)
    }

    /// Restores any domain `Clip` back to the pasteboard based on its type.
    public func restoreClip(_ clip: Clip, to pasteboard: NSPasteboard = .general) throws {
        switch clip.type {
        case .text, .code, .prompt:
            guard let text = clip.textContent else {
                throw ClipboardWriterError.emptyContent
            }
            try writeText(text, to: pasteboard)
            
        case .url:
            guard let urlString = clip.textContent else {
                throw ClipboardWriterError.emptyContent
            }
            try writeURL(urlString, to: pasteboard)
            
        case .image:
            guard let path = clip.imagePath else {
                throw ClipboardWriterError.emptyContent
            }
            try writeImage(filenameOrPath: path, to: pasteboard)
        }
    }
}
